DROP TABLE IF EXISTS DAY;
CREATE TABLE DAY(
ID INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50) NOT NUll,
COLOR VARCHAR(50) NOT NULL
);

CREATE INDEX idx_name 
    ON DAY (name); 

INSERT INTO DAY (NAME ,COLOR) VALUES ('Sunday','Red');
INSERT INTO DAY (NAME ,COLOR) VALUES ('Monday','Yellow');